Repository hellohaptik/chatbot_ner, pull requests merged in 2019-03, with the labels that each got.

#221 Allow detection of person name written in latin script for hindi bots
  ner_v1/detectors/textual/name/hindi_const.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/name/tests/test_cases_person_name.csv
Labels: No lint errors

#216 Add a property_assignor module that reads from csv and assigns properties
  ner_v2/detectors/temporal/date/en/data/properties.csv
  ner_v2/detectors/temporal/date/en/data/range_properties.csv
  ner_v2/detectors/temporal/date/hi/data/properties.csv
  ner_v2/detectors/temporal/date/hi/data/range_properties.csv
  ner_v2/detectors/utils.py
  ner_v2/property_assignor/__init__.py
  ner_v2/property_assignor/fields.py
  ner_v2/property_assignor/property_assignor.py
  ner_v2/property_assignor/reader.py
  ner_v2/property_assignor/utils.py
Labels: No lint errors

#213 Add test cases for date detection
  ner_v2/detectors/temporal/date/en/test.yaml
Labels: No lint errors

#222 Add mergeability and release drafter
  .github/mergeable.yml
  .github/release-drafter.yml
Labels: No lint errors, new-feature

#219 Add airport code CSV
  data/entity_data/airport_code.csv
Labels: enhancement

#225 update units.csv
  ner_v2/detectors/numeral/number/en/data/units.csv
Labels: No lint errors, enhancement

#226 add numerals constant data fix
  ner_v2/detectors/numeral/number/en/data/numerals_constant.csv
  ner_v2/tests/numeral/number/en/test_number_detection.py
Labels: No lint errors, enhancement

#188 Add a code style guideline document
  .pylintrc
  docs/code_style_guide.md
  docs/contributing.md
  docs/haptik_python_best_practices.md
  docs/images/Create-PR.png
  docs/images/Fork-1.png
  docs/images/Fork-2.png
  docs/images/Fork-3.png
  docs/images/PR-Checks.png
  requirements.txt
Labels: No lint errors, documentation, enhancement, miscellaneous

#224 Contribution guidelines overview
  README.md
  docs/images/date_contribution_example.png
Labels: No lint errors, documentation

#229 Added new url call to read unique values for text entity
  chatbot_ner/urls.py
  external_api/api.py
Labels: No lint errors, new-feature

#228 Release 2019-03-20 07:42:41 +0000
  .github/mergeable.yml
  .github/release-drafter.yml
  .pylintrc
  README.md
  chatbot_ner/urls.py
  data/entity_data/airport_code.csv
  datastore/elastic_search/query.py
  docs/api_call.md
  docs/code_style_guide.md
  docs/contributing.md
  docs/haptik_python_best_practices.md
  docs/images/Create-PR.png
  docs/images/Fork-1.png
  docs/images/Fork-2.png
  docs/images/Fork-3.png
  docs/images/PR-Checks.png
  docs/images/date_contribution_example.png
  docs/images/form.png
  external_api/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/textual/name/hindi_const.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/name/tests/test_cases_person_name.csv
  ner_v2/detectors/numeral/number/README.md
  ner_v2/detectors/numeral/number/en/data/numerals_constant.csv
  ner_v2/detectors/numeral/number/en/data/units.csv
  ner_v2/detectors/temporal/constant.py
  ner_v2/detectors/temporal/date/date_detection.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/utils.py
  ner_v2/tests/numeral/number/en/test_number_detection.py
  requirements.txt
Labels: No lint errors, miscellaneous

#230 add shopping quantity units update
  ner_v2/detectors/numeral/number/en/data/units.csv
Labels: No lint errors, enhancement

#231 added one more word for next
  ner_v2/detectors/temporal/date/mr/data/datetime_diff_constant.csv
Labels: No lint errors, enhancement, patterns-data-update

#227 Fix known NER errors
  lib/nlp/regexreplace.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/numeral/budget/budget_detection.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/tests/__init__.py
  ner_v1/tests/numeral/__init__.py
  ner_v1/tests/numeral/budget/__init__.py
  ner_v1/tests/numeral/budget/test_budget_detection.py
  ner_v2/detectors/numeral/number/standard_number_detector.py
Labels: No lint errors, bug-fixes, enhancement
