Repository hellohaptik/chatbot_ner, pull requests merged in 2019-07, with the labels that each got.

#271 Update Django version - Security
  requirements.txt
Labels: No lint errors, enhancement

#276 Django version upgrade
  requirements.txt
Labels: No lint errors, bug-fixes

#284 Add marathi data
  ner_v2/detectors/numeral/number/mr/data/numerals_constant.csv
  ner_v2/detectors/temporal/date/mr/data/date_constant.csv
  ner_v2/detectors/temporal/time/mr/data/datetime_diff_constant.csv
  ner_v2/detectors/temporal/time/mr/data/time_constant.csv
Labels: No lint errors, enhancement

#286 Add telugu date number data
  ner_v2/detectors/numeral/number/te/__init__.py
  ner_v2/detectors/numeral/number/te/data/numerals_constant.csv
  ner_v2/detectors/temporal/date/README.md
  ner_v2/detectors/temporal/date/te/__init__.py
  ner_v2/detectors/temporal/date/te/data/date_constant.csv
  ner_v2/detectors/temporal/date/te/data/datetime_diff_constant.csv
  ner_v2/detectors/temporal/date/te/data/numbers_constant.csv
Labels: No lint errors, enhancement

#287 Add language support to the CRF API
  datastore/datastore.py
  datastore/elastic_search/populate.py
  datastore/elastic_search/query.py
  external_api/api.py
  external_api/constants.py
Labels: No lint errors, enhancement

#288 Revert API body JSON load
  external_api/api.py
Labels: No lint errors, bug-fixes

#289 replace punctuation in original_text while tagging entities
  ner_v1/detectors/textual/text/text_detection.py
Labels: No lint errors, miscellaneous

#291 use regex in place of re module
  ner_v1/detectors/textual/text/text_detection.py
Labels: No lint errors, miscellaneous

#292 Text bulk entity through fallback
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/base_detector.py
Labels: No lint errors, enhancement

#293 Channel number
  ner_v2/detectors/numeral/number/en/data/units.csv
Labels: No lint errors, enhancement

#294 separating channel season episode
  ner_v2/detectors/numeral/number/en/data/units.csv
Labels: No lint errors, bug-fixes

#295 Fix issue in single char scale for number detection
  ner_v2/detectors/numeral/utils.py
Labels: No lint errors, bug-fixes

#296 Channel number
  ner_v2/detectors/numeral/number/gu/data/units.csv
  ner_v2/detectors/numeral/number/hi/data/units.csv
Labels: No lint errors, enhancement, patterns-data-update
