Repository hellohaptik/chatbot_ner, pull requests merged in 2019-06, with the labels that each got.

#257 fixed issues in Readme for CRF Model v2
  models/crf_v2/README.md
Labels: No lint errors, bug-fixes

#258 add config for code coverage
  chatbot_ner/settings.py
  requirements.txt
Labels: No lint errors, enhancement

#260 Add Bulk NER call for detect date, time and number
  chatbot_ner/urls.py
  ner_v2/api.py
  ner_v2/detectors/base_detector.py
Labels: enhancement

#266 Fix scale search and add test cases for all scales of budgets
  ner_v1/detectors/numeral/budget/budget_detection.py
  ner_v1/tests/numeral/budget/test_budget_detection.py
Labels: No lint errors, bug-fixes

#270 Phone number detector bulk messages
  chatbot_ner/urls.py
  ner_v2/api.py
Labels: No lint errors, new-feature

#267 Develop to Master - June 18, 2019
  chatbot_ner/settings.py
  chatbot_ner/urls.py
  models/crf_v2/README.md
  ner_v1/detectors/numeral/budget/budget_detection.py
  ner_v1/tests/numeral/budget/test_budget_detection.py
  ner_v2/api.py
  ner_v2/detectors/base_detector.py
  requirements.txt
Labels: No lint errors, bug-fixes, enhancement, miscellaneous, new-feature
