Repository hellohaptik/chatbot_ner, pull requests merged in 2019-05, with the labels that each got.

#248 Develop to Master 2nd May
  .github/release-drafter.yml
  datastore/constants.py
  datastore/datastore.py
  datastore/elastic_search/__init__.py
  datastore/elastic_search/query.py
  ner_v2/detectors/numeral/number/hi/data/units.csv
  ner_v2/detectors/numeral/number/number_detection.py
  ner_v2/detectors/temporal/date/date_detection.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/date/standard_date_regex.py
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/detectors/temporal/time/standard_time_regex.py
  ner_v2/detectors/temporal/time/time_detection.py
  ner_v2/detectors/temporal/utils.py
Labels: No lint errors, bug-fixes, enhancement, miscellaneous

#249 Added langauge support for indian languages
  language_utilities/constant.py
  ner_v1/detectors/textual/text/text_detection.py
Labels: No lint errors, enhancement

#250 Fix test runner for time detection and fix detected time detection bugs
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/tests/temporal/time/test_time_detection.py
  ner_v2/tests/temporal/time/time_detection_tests.csv
Labels: No lint errors, bug-fixes

#252 Time and Number-range detection test cases in yaml format
  ner_v2/tests/numeral/number/en/number_ner_tests.yaml
  ner_v2/tests/numeral/number/en/test_number_detection.py
  ner_v2/tests/numeral/number_range/number_range_detection_test.csv
  ner_v2/tests/numeral/number_range/number_range_ner_tests.yaml
  ner_v2/tests/numeral/number_range/test_number_range_detection.py
  ner_v2/tests/pattern/phone_number/data/__init__.py
  ner_v2/tests/pattern/phone_number/data/phone_detection_test_cases.csv
  ner_v2/tests/pattern/phone_number/phone_number_ner_tests.yaml
  ner_v2/tests/pattern/phone_number/test_phone_number_detection.py
  ner_v2/tests/temporal/time/test_time_detection.py
  ner_v2/tests/temporal/time/time_detection_tests.csv
  ner_v2/tests/temporal/time/time_ner_tests.yaml
  requirements.txt
Labels: No lint errors, enhancement

#255 Put pos tag logic on higher priority in person name NER
  ner_v1/detectors/textual/name/name_detection.py
Labels: No lint errors, bug-fixes

#256 Develop to master
  language_utilities/constant.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/tests/numeral/number/en/number_ner_tests.yaml
  ner_v2/tests/numeral/number/en/test_number_detection.py
  ner_v2/tests/numeral/number_range/number_range_detection_test.csv
  ner_v2/tests/numeral/number_range/number_range_ner_tests.yaml
  ner_v2/tests/numeral/number_range/test_number_range_detection.py
  ner_v2/tests/pattern/phone_number/data/__init__.py
  ner_v2/tests/pattern/phone_number/data/phone_detection_test_cases.csv
  ner_v2/tests/pattern/phone_number/phone_number_ner_tests.yaml
  ner_v2/tests/pattern/phone_number/test_phone_number_detection.py
  ner_v2/tests/temporal/time/test_time_detection.py
  ner_v2/tests/temporal/time/time_detection_tests.csv
  ner_v2/tests/temporal/time/time_ner_tests.yaml
  requirements.txt
Labels: No lint errors, bug-fixes, enhancement
