Repository hellohaptik/chatbot_ner, pull requests merged in 2019-12, with the labels that each got.

#329 Update requirements for security Vulnerability
  requirements.txt
Labels: No lint errors, bug-fixes, security

#290 Remove SECRET_KEY from settings and move to ENV
  chatbot_ner/config.py
  chatbot_ner/settings.py
  config.example
  docker/Dockerfile
  docs/install.md
Labels: No lint errors, bug-fixes

#330 Update install.md
  docs/install.md
Labels: No lint errors, documentation
