Repository hellohaptik/chatbot_ner, pull requests merged in 2019-04, with the labels that each got.

#233 Bulk detection for text entity
  chatbot_ner/urls.py
  datastore/datastore.py
  datastore/elastic_search/query.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/base_detector.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v1/detectors/textual/text/text_detection_model.py
Labels: No lint errors, new-feature

#235 Number detection fix
  ner_v2/detectors/numeral/number/standard_number_detector.py
Labels: No lint errors, bug-fixes

#237 Develop -> Master
  chatbot_ner/urls.py
  datastore/datastore.py
  datastore/elastic_search/query.py
  lib/nlp/regexreplace.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/base_detector.py
  ner_v1/detectors/numeral/budget/budget_detection.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v1/detectors/textual/text/text_detection_model.py
  ner_v1/tests/__init__.py
  ner_v1/tests/numeral/__init__.py
  ner_v1/tests/numeral/budget/__init__.py
  ner_v1/tests/numeral/budget/test_budget_detection.py
  ner_v2/detectors/numeral/number/en/data/units.csv
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/temporal/date/mr/data/datetime_diff_constant.csv
Labels: No lint errors, bug-fixes, enhancement, miscellaneous

#239 TextDetector - Reset internal state
  ner_v1/detectors/textual/city/city_detection.py
  ner_v1/detectors/textual/text/text_detection.py
Labels: No lint errors, bug-fixes

#240 Develop to Master
  ner_v1/detectors/textual/city/city_detection.py
  ner_v1/detectors/textual/text/text_detection.py
Labels: No lint errors, bug-fixes

#241 Add a get_timezone utils functions to set timezone correctly
  ner_v2/detectors/temporal/date/date_detection.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/date/standard_date_regex.py
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/detectors/temporal/time/standard_time_regex.py
  ner_v2/detectors/temporal/time/time_detection.py
  ner_v2/detectors/temporal/utils.py
Labels: No lint errors, bug-fixes

#243 add shopping quantity units for hindi
  ner_v2/detectors/numeral/number/hi/data/units.csv
Labels: No lint errors, enhancement

#242 Exclude "miscellaneous" pull requests from release notes
  .github/release-drafter.yml
Labels: No lint errors, enhancement

#244 Detect ranges correctly when there are multiple separators
  ner_v2/detectors/temporal/date/date_detection.py
Labels: No lint errors, bug-fixes

#246 Number Detection- Floating point number digits validation
  ner_v2/detectors/numeral/number/number_detection.py
Labels: No lint errors, bug-fixes

#247 Change highlighter, fetch value only in source_ and add deprecation warnings
  datastore/constants.py
  datastore/datastore.py
  datastore/elastic_search/__init__.py
  datastore/elastic_search/query.py
Labels: No lint errors, enhancement
