Repository hellohaptik/chatbot_ner, pull requests merged in 2019-01, with the labels that each got.

#193 Refactor ner_v1.api.text and related methods.
  chatbot_ner/urls.py
  language_utilities/constant.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/base_detector.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v1/detectors/textual/text/text_detection_model.py
  ner_v2/detectors/base_detector.py
Labels: No lint errors

#195 Reliance time fix
  ner_v1/detectors/temporal/time/time_detection.py
  ner_v2/detectors/temporal/time/standard_time_regex.py
Labels: No lint errors

#196 Docker updates
  config.example
  docker/docker-compose.yml
  docs/install.md
Labels: No lint errors

#197 Fix environment variable definition - docker-compose.yml
  docker/docker-compose.yml
Labels: No lint errors

#198 Refactor settings for unit test cases
  __init__.py
  chatbot_ner/settings.py
  ner_v1/detectors/textual/name/tests/test_name_detection.py
  ner_v2/tests/pattern/phone_number/test_phone_number_detection.py
  ner_v2/tests/temporal/date/en/date_detection_test.py
  ner_v2/tests/temporal/date/en/test_date_detection.py
Labels: No lint errors

#189 Number range multilanguage
  chatbot_ner/urls.py
  ner_v2/api.py
  ner_v2/detectors/base_detector.py
  ner_v2/detectors/numeral/constant.py
  ner_v2/detectors/numeral/number/README.md
  ner_v2/detectors/numeral/number/number_detection.py
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/number_range/README.md
  ner_v2/detectors/numeral/number_range/__init__.py
  ner_v2/detectors/numeral/number_range/en/__init__.py
  ner_v2/detectors/numeral/number_range/en/data/__init__.py
  ner_v2/detectors/numeral/number_range/en/data/number_range_keywords.csv
  ner_v2/detectors/numeral/number_range/en/number_range_detection.py
  ner_v2/detectors/numeral/number_range/hi/__init__.py
  ner_v2/detectors/numeral/number_range/hi/data/__init__.py
  ner_v2/detectors/numeral/number_range/hi/data/number_range_keywords.csv
  ner_v2/detectors/numeral/number_range/number_range_detection.py
  ner_v2/detectors/numeral/number_range/standard_number_range_detector.py
  ner_v2/detectors/temporal/constant.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/time/standard_time_regex.py
  ner_v2/detectors/temporal/time/time_detection.py
  ner_v2/detectors/temporal/utils.py
  ner_v2/tests/numeral/number_range/__init__.py
  ner_v2/tests/numeral/number_range/number_range_detection_test.csv
  ner_v2/tests/numeral/number_range/test_number_range_detection.py
Labels: No lint errors

#201 Develop to Master
  chatbot_ner/settings.py
  chatbot_ner/urls.py
  chatbot_ner/wsgi.py
  config.example
  docker/docker-compose.yml
  docs/install.md
  language_utilities/constant.py
  ner_constants.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/constant.py
  ner_v1/detectors/base_detector.py
  ner_v1/detectors/temporal/time/time_detection.py
  ner_v1/detectors/textual/name/hindi_const.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/name/tests/__init__.py
  ner_v1/detectors/textual/name/tests/test_cases_person_name.csv
  ner_v1/detectors/textual/name/tests/test_name_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v1/detectors/textual/text/text_detection_model.py
  ner_v2/api.py
  ner_v2/detectors/base_detector.py
  ner_v2/detectors/numeral/constant.py
  ner_v2/detectors/numeral/number/README.md
  ner_v2/detectors/numeral/number/bn/data/units.csv
  ner_v2/detectors/numeral/number/en/data/units.csv
  ner_v2/detectors/numeral/number/en/number_detection.py
  ner_v2/detectors/numeral/number/gu/data/units.csv
  ner_v2/detectors/numeral/number/hi/data/units.csv
  ner_v2/detectors/numeral/number/mr/data/units.csv
  ner_v2/detectors/numeral/number/number_detection.py
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/number/ta/data/units.csv
  ner_v2/detectors/numeral/number_range/README.md
  ner_v2/detectors/numeral/number_range/__init__.py
  ner_v2/detectors/numeral/number_range/en/__init__.py
  ner_v2/detectors/numeral/number_range/en/data/__init__.py
  ner_v2/detectors/numeral/number_range/en/data/number_range_keywords.csv
  ner_v2/detectors/numeral/number_range/en/number_range_detection.py
  ner_v2/detectors/numeral/number_range/hi/__init__.py
  ner_v2/detectors/numeral/number_range/hi/data/__init__.py
  ner_v2/detectors/numeral/number_range/hi/data/number_range_keywords.csv
  ner_v2/detectors/numeral/number_range/number_range_detection.py
  ner_v2/detectors/numeral/number_range/standard_number_range_detector.py
  ner_v2/detectors/pattern/phone_number/phone_number_detection.py
  ner_v2/detectors/temporal/constant.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/time/standard_time_regex.py
  ner_v2/detectors/temporal/time/time_detection.py
  ner_v2/detectors/temporal/utils.py
  ner_v2/tests/numeral/number_range/__init__.py
  ner_v2/tests/numeral/number_range/number_range_detection_test.csv
  ner_v2/tests/numeral/number_range/test_number_range_detection.py
  ner_v2/tests/pattern/phone_number/test_phone_number_detection.py
  ner_v2/tests/temporal/date/en/date_detection_test.py
  ner_v2/tests/temporal/date/en/test_date_detection.py
  requirements.txt
Labels: New Feature, enhancement

#194 Initial set of API calls for fetching dictionary data
  .gitignore
  chatbot_ner/urls.py
  datastore/datastore.py
  datastore/elastic_search/populate.py
  datastore/elastic_search/query.py
  datastore/exceptions.py
  external_api/README.md
  external_api/api.py
  external_api/exceptions.py
  external_api/lib/__init__.py
  external_api/lib/dictionary_utils.py
  external_api/response_utils.py
Labels: No lint errors, enhancement

#202 Update conditions when pagination should be done for dictionary search
  external_api/lib/dictionary_utils.py
Labels: No lint errors
