Repository hellohaptik/chatbot_ner, pull requests merged in 2020-01, with the labels that each got.

#332 add new version of django upgrade for security
  requirements.txt
Labels: No lint errors, enhancement, security

#331 Add .vscode to gitignore
  .gitignore
Labels: enhancement

#328 Allow Text and Name Detectors to process pre-detected values
  ner_constants.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/constant.py
  ner_v1/detectors/base_detector.py
  ner_v1/detectors/textual/name/hindi_const.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/name/tests/test_cases_person_name.csv
  ner_v1/detectors/textual/name/tests/test_name_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v1/detectors/textual/text/text_detection_model.py
Labels: enhancement

#333 Lint fixes and Master to Develop
  ner_v1/detectors/textual/name/name_detection.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/date/standard_date_regex.py
Labels: No lint errors, miscellaneous

#334 Add hindi detection tags for name detection
  ner_v1/detectors/textual/name/hindi_const.py
Labels: No lint errors, enhancement

#335 NameDetector - Standalone name detection restriction
  ner_v1/detectors/textual/name/name_detection.py
Labels: No lint errors, bug-fixes

#336 Fix name detection test case
  ner_v1/detectors/textual/name/tests/test_name_detection.py
Labels: No lint errors, bug-fixes

#337 Fix lint errors
  ner_v1/detectors/textual/name/tests/test_name_detection.py
Labels: No lint errors, code-cleanup, miscellaneous

#326 Develop to Master
  .gitignore
  chatbot_ner/config.py
  chatbot_ner/settings.py
  config.example
  docker/Dockerfile
  docs/install.md
  ner_constants.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/constant.py
  ner_v1/detectors/base_detector.py
  ner_v1/detectors/textual/name/hindi_const.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/name/tests/test_cases_person_name.csv
  ner_v1/detectors/textual/name/tests/test_name_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v1/detectors/textual/text/text_detection_model.py
  ner_v2/api.py
  ner_v2/detectors/temporal/date/date_detection.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/date/hi/date_detection.py
  ner_v2/detectors/temporal/date/standard_date_regex.py
  ner_v2/tests/temporal/date/en/test_date_detection.py
  requirements.txt
Labels: No lint errors, bug-fixes, enhancement
