Repository hellohaptik/chatbot_ner, pull requests merged in 2020-05, with the labels that each got.

#359 Develop to Master
  .gitignore
  .pylintrc
  chatbot_ner/config.py
  chatbot_ner/settings.py
  config.example
  datastore/constants.py
  datastore/datastore.py
  datastore/elastic_search/create.py
  datastore_setup.py
  docker/Dockerfile
  docker/Dockerfile-python3
  docker/cmd.sh
  docker/docker-compose.yml
  docs/datastore_variables.md
  docs/install.md
  external_api/response_utils.py
  initial_setup.py
  ner_v1/detectors/temporal/date/date_detection.py
  ner_v1/detectors/temporal/time/time_detection.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/tests/temporal/time/test_time_detection.py
  ner_v2/tests/temporal/time/time_ner_tests.yaml
  nltk_setup.py
  postman_tests/Readme.md
  postman_tests/config/test_env.json
  postman_tests/data/datastore/ner_ptest_city_list.csv
  postman_tests/data/datastore/ner_ptest_restaurant.csv
  postman_tests/data/entities/budget.json
  postman_tests/data/entities/city.json
  postman_tests/data/entities/date.json
  postman_tests/data/entities/dateV2.json
  postman_tests/data/entities/email.json
  postman_tests/data/entities/number.json
  postman_tests/data/entities/numberV2.json
  postman_tests/data/entities/number_range.json
  postman_tests/data/entities/person_name.json
  postman_tests/data/entities/phoneV1.json
  postman_tests/data/entities/phoneV2.json
  postman_tests/data/entities/pnr.json
  postman_tests/data/entities/regex.json
  postman_tests/data/entities/text_city.json
  postman_tests/data/entities/text_restaurant.json
  postman_tests/data/entities/time.json
  postman_tests/data/entities/timeV2.json
  postman_tests/data/entities/time_range.json
  postman_tests/data/ner_collection.json
  postman_tests/lib/__init__.py
  postman_tests/lib/common.py
  postman_tests/lib/datastore.py
  postman_tests/lib/newman.py
  postman_tests/newman.png
  postman_tests/run_postman_tests.py
  run_postman_tests.sh
Labels: bug-fixes, enhancement, python3-upgrade

#362 Set DEBUG=False, no more configurable from .env
  chatbot_ner/settings.py
  config.example
Labels: No lint errors, miscellaneous

#363 Minor update to install.md
  docs/install.md
Labels: No lint errors, enhancement

#365 fix(regex-detector): Fix MemoryError caused by recursive replace and limit max_matches to 50 by default
  ner_v1/detectors/pattern/regex/regex_detection.py
  ner_v1/tests/pattern/__init__.py
  ner_v1/tests/pattern/regex/__init__.py
  ner_v1/tests/pattern/regex/test_regex_detection.py
  ner_v2/tests/numeral/number/en/test_number_detection.py
  ner_v2/tests/numeral/number_range/test_number_range_detection.py
  ner_v2/tests/pattern/phone_number/test_phone_number_detection.py
  ner_v2/tests/temporal/time/test_time_detection.py
Labels: No lint errors, bug-fixes

#360 Cleanup - Remove gunicorn and start_server.sh
  .gitignore
  chatbot_ner/settings.py
  docker/Dockerfile
  docker/Dockerfile-python3
  requirements.txt
  start_server.sh
Labels: No lint errors, code-cleanup, miscellaneous

#367 Develop to Master
  .gitignore
  chatbot_ner/settings.py
  config.example
  docker/Dockerfile
  docker/Dockerfile-python3
  docs/install.md
  ner_v1/detectors/pattern/regex/regex_detection.py
  ner_v1/tests/pattern/__init__.py
  ner_v1/tests/pattern/regex/__init__.py
  ner_v1/tests/pattern/regex/test_regex_detection.py
  ner_v2/tests/numeral/number/en/test_number_detection.py
  ner_v2/tests/numeral/number_range/test_number_range_detection.py
  ner_v2/tests/pattern/phone_number/test_phone_number_detection.py
  ner_v2/tests/temporal/time/test_time_detection.py
  requirements.txt
  start_server.sh
Labels: No lint errors, bug-fixes, code-cleanup, miscellaneous
