Repository hellohaptik/chatbot_ner, pull requests merged in 2020-03, with the labels that each got.

#345 3rd set of python 2 and 3 compatible changes
  ner_v1/detectors/textual/city/city_detection.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v2/detectors/numeral/number_range/en/number_range_detection.py
  ner_v2/detectors/numeral/number_range/standard_number_range_detector.py
  requirements.txt
Labels: No lint errors, enhancement

#348 Updated log handler to watcher
  chatbot_ner/config.py
Labels: No lint errors, enhancement, miscellaneous

#350 Add u prefix to fix syntax error
  ner_v1/detectors/textual/city/city_detection.py
Labels: No lint errors, bug-fixes

#349 Added canadian dollar currency
  ner_v2/detectors/numeral/number/en/data/units.csv
Labels: No lint errors, bug-fixes

#351 Final set of changes for python 3 upgrade of chatbot ner
  chatbot_ner/config.py
  ner_v1/detectors/textual/city/city_detection.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v2/detectors/numeral/number/en/data/units.csv
  ner_v2/detectors/numeral/number_range/en/number_range_detection.py
  ner_v2/detectors/numeral/number_range/standard_number_range_detector.py
  requirements.txt
Labels: No lint errors, enhancement
