Repository hellohaptik/chatbot_ner, pull requests merged in 2020-09, with the labels that each got.

#376 Add support standalone es datastore for multi entity text detection
  chatbot_ner/urls.py
  ner_v2/api.py
  ner_v2/detectors/textual/__init__.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/queries.py
  ner_v2/detectors/textual/tests/__init__.py
  ner_v2/detectors/textual/tests/query_generate_output_entity_list_data.json
  ner_v2/detectors/textual/tests/query_generate_output_entity_string_data.json
  ner_v2/detectors/textual/tests/query_parse_input_data.json
  ner_v2/detectors/textual/tests/query_parse_output_data.json
  ner_v2/detectors/textual/tests/test_elastic_search.py
  ner_v2/detectors/textual/tests/test_queries.py
Labels: No lint errors, enhancement, miscellaneous

#377 Add support for text detetction for multi entity multi text in ner_v2
  ner_constants.py
  ner_v2/api.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/tests/test_elastic_search.py
  ner_v2/detectors/textual/tests/test_text_detection.py
  ner_v2/detectors/textual/tests/test_utils.py
  ner_v2/detectors/textual/text_detection.py
  ner_v2/detectors/textual/utils.py
Labels: No lint errors, enhancement, miscellaneous, new-feature

#375 Develop to Master
  .github/pull_request_template.md
  chatbot_ner/urls.py
  config.example
  datastore/datastore.py
  datastore/elastic_search/create.py
  ner_constants.py
  ner_v2/api.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/textual/__init__.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/queries.py
  ner_v2/detectors/textual/tests/__init__.py
  ner_v2/detectors/textual/tests/query_generate_output_entity_list_data.json
  ner_v2/detectors/textual/tests/query_generate_output_entity_string_data.json
  ner_v2/detectors/textual/tests/query_parse_input_data.json
  ner_v2/detectors/textual/tests/query_parse_output_data.json
  ner_v2/detectors/textual/tests/test_elastic_search.py
  ner_v2/detectors/textual/tests/test_queries.py
  ner_v2/detectors/textual/tests/test_text_detection.py
  ner_v2/detectors/textual/tests/test_utils.py
  ner_v2/detectors/textual/text_detection.py
  ner_v2/detectors/textual/utils.py
  postman_tests/data/entities/date.json
  postman_tests/data/entities/dateV2.json
  requirements.txt
Labels: bug-fixes, code-cleanup, miscellaneous, new-feature
