Repository hellohaptik/chatbot_ner, pull requests merged in 2020-02, with the labels that each got.

#338 Return type fix in TextDetector.detect_entity
  ner_v1/detectors/numeral/budget/budget_detection.py
  ner_v1/detectors/numeral/size/shopping_size_detection.py
  ner_v1/detectors/textual/city/city_detection.py
  ner_v1/detectors/textual/text/text_detection.py
Labels: No lint errors, bug-fixes

#339 Master to Develop
  ner_v1/detectors/numeral/budget/budget_detection.py
  ner_v1/detectors/numeral/size/shopping_size_detection.py
  ner_v1/detectors/textual/city/city_detection.py
  ner_v1/detectors/textual/text/text_detection.py
Labels: No lint errors, bug-fixes

#341 Fix regex pattern in name_detection.py
  ner_v1/detectors/textual/name/name_detection.py
Labels: No lint errors, bug-fixes, miscellaneous

#342 1st set of Python 2 and 3 compatible changes
  datastore/elastic_search/create.py
  datastore/elastic_search/populate.py
  datastore/elastic_search/query.py
  datastore/elastic_search/transfer.py
  docker/Dockerfile-python3
  lib/nlp/levenshtein_distance.py
  models/crf/test.py
  models/crf_v2/crf_detect_entity.py
  models/crf_v2/crf_preprocess_data.py
  models/crf_v2/crf_train.py
  ner_v1/chatbot/combine_detection_logic.py
  ner_v1/detectors/base_detector.py
  ner_v1/detectors/numeral/budget/budget_detection.py
  ner_v1/detectors/temporal/date/date_detection.py
  ner_v1/detectors/temporal/time/time_detection.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/name/tests/test_name_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v2/detectors/numeral/number/number_detection.py
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/number_range/standard_number_range_detector.py
  ner_v2/detectors/numeral/utils.py
  ner_v2/detectors/pattern/phone_number/phone_number_detection.py
  ner_v2/detectors/temporal/date/date_detection.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/detectors/temporal/utils.py
  ner_v2/tests/numeral/number/en/test_number_detection.py
Labels: enhancement, miscellaneous, python3-upgrade

#343 Develop to Master
  datastore/elastic_search/create.py
  datastore/elastic_search/populate.py
  datastore/elastic_search/query.py
  datastore/elastic_search/transfer.py
  docker/Dockerfile-python3
  lib/nlp/levenshtein_distance.py
  models/crf/test.py
  models/crf_v2/crf_detect_entity.py
  models/crf_v2/crf_preprocess_data.py
  models/crf_v2/crf_train.py
  ner_v1/chatbot/combine_detection_logic.py
  ner_v1/detectors/base_detector.py
  ner_v1/detectors/numeral/budget/budget_detection.py
  ner_v1/detectors/temporal/date/date_detection.py
  ner_v1/detectors/temporal/time/time_detection.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/detectors/textual/name/tests/test_name_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v2/detectors/numeral/number/number_detection.py
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/number_range/standard_number_range_detector.py
  ner_v2/detectors/numeral/utils.py
  ner_v2/detectors/pattern/phone_number/phone_number_detection.py
  ner_v2/detectors/temporal/date/date_detection.py
  ner_v2/detectors/temporal/date/en/date_detection.py
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/detectors/temporal/utils.py
  ner_v2/tests/numeral/number/en/test_number_detection.py
Labels: bug-fixes, enhancement, python3-upgrade
