Repository hellohaptik/chatbot_ner, pull requests merged in 2021-06, with the labels that each got.

#431 Adding Previous Messages + Refactoring
  ner_v1/detectors/textual/name/lang_constants.py
  ner_v1/detectors/textual/name/name_detection.py
Labels: enhancement

#434 Move log line from .info to .debug for less spam
  ner_v1/chatbot/entity_detection.py
Labels: No lint errors, code-cleanup, miscellaneous

#432 Enable Full Sentence as Entity for Additional Languages
  language_utilities/constant.py
  ner_v1/detectors/textual/name/lang_constants.py
  ner_v1/detectors/textual/name/name_detection.py
Labels: No lint errors, enhancement

#435 Develop to Master
  language_utilities/constant.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/textual/name/lang_constants.py
  ner_v1/detectors/textual/name/name_detection.py
Labels: No lint errors, miscellaneous

#436 ignore elastic apm errors for sentry
  chatbot_ner/setup_sentry.py
Labels: No lint errors, enhancement
