Repository hellohaptik/chatbot_ner, pull requests merged in 2021-09, with the labels that each got.

#418 Removed unused crf code
  .gitignore
  chatbot_ner/config.py
  chatbot_ner/settings.py
  chatbot_ner/urls.py
  config.example
  docker/Dockerfile
  docker/Dockerfile-python3
  docker/install.sh
  external_api/api.py
  external_api/constants.py
  lib/aws_utils.py
  model_config.example
  models/__init__.py
  models/crf/__init__.py
  models/crf/constant.py
  models/crf/models.py
  models/crf/output_generation/__init__.py
  models/crf/output_generation/city.py
  models/crf/output_generation/date.py
  models/crf/test.py
  models/crf/train.py
  models/crf_v2/README.md
  models/crf_v2/__init__.py
  models/crf_v2/constants.py
  models/crf_v2/crf_detect_entity.py
  models/crf_v2/crf_preprocess_data.py
  models/crf_v2/crf_train.py
  models/crf_v2/exceptions.py
  models/crf_v2/get_crf_tagger.py
  models/crf_v2/load_word_embeddings.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/constant.py
  ner_v1/detectors/temporal/date/date_detection.py
  ner_v1/detectors/textual/city/city_detection.py
  ner_v2/detectors/temporal/date/date_detection.py
  requirements.txt
Labels: enhancement, No lint errors, code-cleanup

#440 Update previous context tag constant for person name
  ner_v1/detectors/textual/name/lang_constants.py
Labels: bug-fixes, No lint errors

#441 Develop to Master: September 19
  .gitignore
  chatbot_ner/config.py
  chatbot_ner/settings.py
  chatbot_ner/setup_sentry.py
  chatbot_ner/urls.py
  config.example
  docker/Dockerfile
  docker/Dockerfile-python3
  docker/install.sh
  external_api/api.py
  external_api/constants.py
  lib/aws_utils.py
  model_config.example
  models/__init__.py
  models/crf/__init__.py
  models/crf/constant.py
  models/crf/models.py
  models/crf/output_generation/__init__.py
  models/crf/output_generation/city.py
  models/crf/output_generation/date.py
  models/crf/test.py
  models/crf/train.py
  models/crf_v2/README.md
  models/crf_v2/__init__.py
  models/crf_v2/constants.py
  models/crf_v2/crf_detect_entity.py
  models/crf_v2/crf_preprocess_data.py
  models/crf_v2/crf_train.py
  models/crf_v2/exceptions.py
  models/crf_v2/get_crf_tagger.py
  models/crf_v2/load_word_embeddings.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/constant.py
  ner_v1/detectors/temporal/date/date_detection.py
  ner_v1/detectors/textual/city/city_detection.py
  ner_v1/detectors/textual/name/lang_constants.py
  ner_v2/detectors/temporal/date/date_detection.py
  requirements.txt
Labels: miscellaneous
