Repository hellohaptik/chatbot_ner, pull requests merged in 2021-05, with the labels that each got.

#428 Drop Elasticsearch client instance if ping fails and raise exception
  chatbot_ner/config.py
  chatbot_ner/urls.py
  external_api/api.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/tests/test_elastic_search.py
Labels: No lint errors, bug-fixes

#427 Develop to Master 2021-04-29T19:39:00
  chatbot_ner/config.py
  chatbot_ner/urls.py
  datastore_exceptions.py
  external_api/api.py
  lib/nlp/tokenizer.py
  ner_v1/detectors/pattern/regex/regex_detection.py
  ner_v1/tests/pattern/regex/test_regex_detection.py
  ner_v2/detectors/pattern/phone_number/phone_number_detection.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/tests/test_elastic_search.py
Labels: No lint errors, miscellaneous

#429 Replace context tag constant for marathi language
  ner_v1/detectors/textual/name/lang_constants.py
Labels: No lint errors, bug-fixes, miscellaneous
