Repository hellohaptik/chatbot_ner, pull requests merged in 2021-03, with the labels that each got.

#391 Updated release drafter to enable Miscellaneous label as a normal category
  .github/release-drafter.yml
Labels: No lint errors, enhancement

#393 Add elastic APM config changes
  chatbot_ner/settings.py
  requirements.txt
Labels: No lint errors, enhancement

#416 Bug fixes for v2/number, v2/number_range, v2/time
  .coveragerc
  .gitignore
  chatbot_ner/config.py
  chatbot_ner/settings.py
  chatbot_ner/setup_sentry.py
  logs/.gitkeep
  ner_v1/detectors/textual/name/lang_constants.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/static/index.html
  ner_v1/static/ner_dashboard.css
  ner_v1/static/ner_dashboard.js
  ner_v2/api.py
  ner_v2/detectors/numeral/number/hi/data/numerals_constant.csv
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/number_range/README.md
  ner_v2/detectors/numeral/number_range/en/number_range_detection.py
  ner_v2/detectors/numeral/number_range/hi/data/number_range_keywords.csv
  ner_v2/detectors/numeral/number_range/standard_number_range_detector.py
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/tests/numeral/number/en/number_ner_tests.yaml
  ner_v2/tests/numeral/number/en/test_number_detection.py
  ner_v2/tests/numeral/number_range/number_range_ner_tests.yaml
  ner_v2/tests/numeral/number_range/test_number_range_detection.py
  ner_v2/tests/pattern/phone_number/test_phone_number_detection.py
  ner_v2/tests/temporal/time/test_time_detection.py
  ner_v2/tests/temporal/time/time_ner_tests.yaml
  postman_tests/data/entities/numberV2.json
  requirements.txt
Labels: No lint errors, bug-fixes, packages-updated

#417 Develop to Master 2021-03-04T13:57:00
  .coveragerc
  .github/release-drafter.yml
  .gitignore
  .whitesource
  chatbot_ner/config.py
  chatbot_ner/settings.py
  chatbot_ner/setup_sentry.py
  logs/.gitkeep
  ner_v1/detectors/textual/name/lang_constants.py
  ner_v1/detectors/textual/name/name_detection.py
  ner_v1/static/index.html
  ner_v1/static/ner_dashboard.css
  ner_v1/static/ner_dashboard.js
  ner_v2/api.py
  ner_v2/detectors/numeral/number/hi/data/numerals_constant.csv
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/number_range/README.md
  ner_v2/detectors/numeral/number_range/en/number_range_detection.py
  ner_v2/detectors/numeral/number_range/hi/data/number_range_keywords.csv
  ner_v2/detectors/numeral/number_range/standard_number_range_detector.py
  ner_v2/detectors/temporal/time/en/time_detection.py
  ner_v2/tests/numeral/number/en/number_ner_tests.yaml
  ner_v2/tests/numeral/number/en/test_number_detection.py
  ner_v2/tests/numeral/number_range/number_range_ner_tests.yaml
  ner_v2/tests/numeral/number_range/test_number_range_detection.py
  ner_v2/tests/pattern/phone_number/test_phone_number_detection.py
  ner_v2/tests/temporal/time/test_time_detection.py
  ner_v2/tests/temporal/time/time_ner_tests.yaml
  postman_tests/data/entities/numberV2.json
  requirements.txt
Labels: No lint errors, miscellaneous

#419 fix(v2/number): cast to int directly if no decimal point is found to avoid wrong values because of precision loss
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/utils.py
  ner_v2/tests/numeral/number/en/number_ner_tests.yaml
  ner_v2/tests/numeral/number/en/test_number_detection.py
Labels: No lint errors, bug-fixes

#420 Develop to Master 2021-03-08T09:36:00
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/utils.py
  ner_v2/tests/numeral/number/en/number_ner_tests.yaml
  ner_v2/tests/numeral/number/en/test_number_detection.py
Labels: No lint errors, miscellaneous

#392 Handle multiple dashes in phone number detection in english
  ner_v2/detectors/pattern/phone_number/phone_number_detection.py
Labels: No lint errors, bug-fixes

#366 Bump pandas from 0.19 to 0.21, numpy from 1.16 to 1.16.5
  requirements.txt
Labels: No lint errors, enhancement, packages-updated

#421 fix(search): search on .keyword if value search term contains whitespace
  datastore/elastic_search/query.py
Labels: No lint errors, bug-fixes
