Repository hellohaptik/chatbot_ner, pull requests merged in 2021-04, with the labels that each got.

#422 Support for better handling error from ES search
  datastore/elastic_search/query.py
  datastore/exceptions.py
  ner_v1/api.py
  ner_v2/api.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/queries.py
  ner_v2/detectors/textual/tests/test_utils.py
  ner_v2/detectors/textual/utils.py
Labels: No lint errors, enhancement

#424 Develop to Master Sync
  datastore/elastic_search/query.py
  datastore/exceptions.py
  ner_v1/api.py
  ner_v2/api.py
  ner_v2/detectors/pattern/phone_number/phone_number_detection.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/queries.py
  ner_v2/detectors/textual/tests/test_utils.py
  ner_v2/detectors/textual/utils.py
  requirements.txt
Labels: No lint errors, bug-fixes, enhancement

#426 Try compiling with `regex.V0` engine if `regex.V1` fails
  datastore_exceptions.py
  lib/nlp/tokenizer.py
  ner_v1/detectors/pattern/regex/regex_detection.py
  ner_v1/tests/pattern/regex/test_regex_detection.py
  ner_v2/detectors/pattern/phone_number/phone_number_detection.py
Labels: No lint errors, bug-fixes
