Repository hellohaptik/chatbot_ner, pull requests merged in 2022-04, with the labels that each got.

#475 Build ASR Support for Regex, Email. Enhance Number, Date Entity
  lib/nlp/levenshtein_distance.py
  lib/nlp/text_normalization.py
  ner_constants.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/pattern/email/email_detection.py
  ner_v1/detectors/pattern/regex/data/__init__.py
  ner_v1/detectors/pattern/regex/data/character_constants.py
  ner_v1/detectors/pattern/regex/regex_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v2/detectors/numeral/constant.py
  ner_v2/detectors/numeral/number/en/data/numerals_constant.csv
  ner_v2/detectors/numeral/number/hi/data/numerals_constant.csv
  ner_v2/detectors/numeral/number/number_detection.py
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/utils.py
  ner_v2/detectors/temporal/date/hi/data/date_constant.csv
  ner_v2/detectors/textual/text_detection.py
Labels: new-feature

#478 Develop to Master 21-04-22
  lib/nlp/levenshtein_distance.py
  lib/nlp/text_normalization.py
  ner_constants.py
  ner_v1/api.py
  ner_v1/chatbot/entity_detection.py
  ner_v1/detectors/pattern/email/email_detection.py
  ner_v1/detectors/pattern/regex/data/__init__.py
  ner_v1/detectors/pattern/regex/data/character_constants.py
  ner_v1/detectors/pattern/regex/regex_detection.py
  ner_v1/detectors/textual/text/text_detection.py
  ner_v2/detectors/numeral/constant.py
  ner_v2/detectors/numeral/number/en/data/numerals_constant.csv
  ner_v2/detectors/numeral/number/hi/data/numerals_constant.csv
  ner_v2/detectors/numeral/number/number_detection.py
  ner_v2/detectors/numeral/number/standard_number_detector.py
  ner_v2/detectors/numeral/utils.py
  ner_v2/detectors/temporal/date/hi/data/date_constant.csv
  ner_v2/detectors/textual/text_detection.py
Labels: enhancement, new-feature, miscellaneous

#480 Bug-fix: Decimals concatenating
  ner_v2/detectors/numeral/number/number_detection.py
Labels: bug-fixes, No lint errors

#481 Develop -> Master
  ner_v2/detectors/numeral/number/number_detection.py
Labels: bug-fixes, No lint errors, miscellaneous

#486 Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement, No lint errors
