Repository hellohaptik/chatbot_ner, pull requests merged in 2022-07, with the labels that each got.

#490 Hotfix: Temporary increase in maximum entities allowed
  ner_constants.py
  ner_v2/detectors/textual/utils.py
Labels: bug-fixes, No lint errors

#491 Backmerge Master -> Develop
  ner_constants.py
  ner_v2/detectors/textual/utils.py
Labels: No lint errors, miscellaneous

#494 Sentry setup configuration changes
  chatbot_ner/setup_sentry.py
Labels: bug-fixes, No lint errors

#495 Develop to master
  chatbot_ner/setup_sentry.py
Labels: miscellaneous
