Repository hellohaptik/chatbot_ner, pull requests merged in 2023-10, with the labels that each got.

#544 (adhoc)(platform-support) Add logs for debugging the entity detection issue for NSDC
  docker/Dockerfile
  ner_v2/api.py
  ner_v2/detectors/textual/text_detection.py
  ner_v2/detectors/textual/utils.py
Labels: No lint errors, miscellaneous

#545 (misc:) Log results from ES for chosen entities
  ner_v2/detectors/textual/elastic_search.py
Labels: No lint errors, miscellaneous

#546 (misc) Update log level from debug to info
  ner_v2/api.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/utils.py
Labels: No lint errors, miscellaneous

#547 Backmerge
  docker/Dockerfile
  ner_v2/api.py
  ner_v2/detectors/textual/elastic_search.py
  ner_v2/detectors/textual/text_detection.py
  ner_v2/detectors/textual/utils.py
Labels: No lint errors, missing-tests, dont-test, missing-labels

#552 Updated logs for text entity
  ner_v2/detectors/textual/elastic_search.py
Labels: enhancement

#554 Added logs for text entity detection
  ner_v2/detectors/textual/text_detection.py
  ner_v2/detectors/textual/utils.py
Labels: miscellaneous
